using System.Reflection;
[assembly: System.Reflection.AssemblyTitle("BAR Editor")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 GovanifY 2013")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyCompany("GovanifY")]
[assembly: System.Reflection.AssemblyProduct("BAR Editor")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("c38bee49-47ce-45c9-982d-a868c53b4b52")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.0.0")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]

[assembly: AssemblyVersionAttribute("1.1.0.0")]
