using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using khiiMapv.CollTest;
using khiiMapv.Properties;
using Readmset;

namespace khiiMapv
{
    partial class RDForm
    {
        private const int BASE = 144;
        private ImageList IL;
        private WavePlayerDelegate WavePlayer;
        private List<DC> aldc = new List<DC>();
        private LinkLabel bBatExp;
        private Button bExportAll;
        private Button bExportBin;
        private Button bserr;
        private Button button1;
        private CollReader coll = new CollReader();
        private IContainer components;
        private SortedDictionary<int, string> dictObjName = new SortedDictionary<int, string>();
        private ListDictionary errcol = new ListDictionary();
        private string fpld;
        private string fpread;
        private HexVwer hv1;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label labelHelpMore;
        private Label labelPixi;
        private LinkLabel linkLabel1;
        private ListView lvMI;
        private Panel p1;
        private byte[] rdbin = new byte[0];
        private TreeView treeView1;
        private Visf visf;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new Container();
            var componentResourceManager = new ComponentResourceManager(typeof(RDForm));
            treeView1 = new TreeView();
            IL = new ImageList(components);
            linkLabel1 = new LinkLabel();
            p1 = new Panel();
            lvMI = new ListView();
            button1 = new Button();
            label1 = new Label();
            label2 = new Label();
            bserr = new Button();
            label3 = new Label();
            labelPixi = new Label();
            labelHelpMore = new Label();
            bExportBin = new Button();
            hv1 = new HexVwer();
            bExportAll = new Button();
            bBatExp = new LinkLabel();
            base.SuspendLayout();
            treeView1.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            treeView1.ImageIndex = 0;
            treeView1.ImageList = IL;
            treeView1.Location = new Point(12, 23);
            treeView1.Name = "treeView1";
            treeView1.SelectedImageIndex = 0;
            treeView1.Size = new Size(246, 263);
            treeView1.TabIndex = 1;
            treeView1.DoubleClick += treeView1_DoubleClick;
            treeView1.AfterSelect += treeView1_AfterSelect;
            IL.TransparentColor = Color.Magenta;
            linkLabel1.AutoSize = true;
            linkLabel1.Location = new Point(12, 9);
            linkLabel1.Name = "linkLabel1";
            linkLabel1.Size = new Size(56, 12);
            linkLabel1.TabIndex = 0;
            linkLabel1.TabStop = true;
            linkLabel1.Text = "linkLabel1";
            p1.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            p1.AutoScroll = true;
            p1.BorderStyle = BorderStyle.FixedSingle;
            p1.Location = new Point(264, 24);
            p1.Name = "p1";
            p1.Size = new Size(370, 262);
            p1.TabIndex = 2;
            lvMI.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Right);
            lvMI.HideSelection = false;
            lvMI.Location = new Point(640, 322);
            lvMI.MultiSelect = false;
            lvMI.Name = "lvMI";
            lvMI.Size = new Size(53, 252);
            lvMI.TabIndex = 10;
            lvMI.UseCompatibleStateImageBehavior = false;
            lvMI.View = View.List;
            lvMI.SelectedIndexChanged += lvMI_SelectedIndexChanged;
            button1.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
            button1.FlatStyle = FlatStyle.Flat;
            button1.Location = new Point(640, 24);
            button1.Name = "button1";
            button1.Size = new Size(59, 56);
            button1.TabIndex = 3;
            button1.Text = "Map &viewer";
            button1.UseVisualStyleBackColor = true;
            button1.Click += button1_Click;
            label1.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            label1.AutoSize = true;
            label1.Location = new Point(12, 578);
            label1.Name = "label1";
            label1.Size = new Size(295, 12);
            label1.TabIndex = 11;
            label1.Text = "* Drop a map file to window. Then click \"viewer\" button.";
            label2.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            label2.AutoSize = true;
            label2.Location = new Point(12, 596);
            label2.Margin = new Padding(3, 6, 3, 0);
            label2.Name = "label2";
            label2.Size = new Size(423, 12);
            label2.TabIndex = 12;
            label2.Text = "* Currently accepts map mdlx apdx fm 2dd bar 2ld mset pax wd vsb ard imd mag";
            bserr.ImageAlign = ContentAlignment.MiddleRight;
            bserr.Location = new Point(12, 292);
            bserr.Name = "bserr";
            bserr.Size = new Size(131, 23);
            bserr.TabIndex = 7;
            bserr.Text = "Show error popup";
            bserr.TextAlign = ContentAlignment.MiddleLeft;
            bserr.UseVisualStyleBackColor = true;
            bserr.Visible = false;
            bserr.Click += bserr_Click;
            label3.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
            label3.AutoSize = true;
            label3.Location = new Point(640, 83);
            label3.Name = "label3";
            label3.Size = new Size(55, 12);
            label3.TabIndex = 4;
            label3.Text = "Pixel info:";
            labelPixi.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
            labelPixi.AutoSize = true;
            labelPixi.Location = new Point(640, 95);
            labelPixi.Name = "labelPixi";
            labelPixi.Size = new Size(11, 96);
            labelPixi.TabIndex = 5;
            labelPixi.Text = "...\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n";
            labelHelpMore.Font = new Font("ＭＳ ゴシック", 9f, FontStyle.Regular, GraphicsUnit.Point, 128);
            labelHelpMore.Location = new Point(149, 289);
            labelHelpMore.Name = "labelHelpMore";
            labelHelpMore.Size = new Size(544, 30);
            labelHelpMore.TabIndex = 8;
            labelHelpMore.Text = "...";
            bExportBin.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
            bExportBin.FlatStyle = FlatStyle.Flat;
            bExportBin.Location = new Point(640, 194);
            bExportBin.Name = "bExportBin";
            bExportBin.Size = new Size(59, 40);
            bExportBin.TabIndex = 6;
            bExportBin.Text = "&Export bin";
            bExportBin.UseVisualStyleBackColor = true;
            bExportBin.Click += bExportBin_Click;
            hv1.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            hv1.AntiFlick = true;
            hv1.BorderStyle = BorderStyle.FixedSingle;
            hv1.ByteWidth = 16;
            hv1.Font = new Font("Courier New", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            hv1.Location = new Point(12, 322);
            hv1.Margin = new Padding(3, 4, 3, 4);
            hv1.Name = "hv1";
            hv1.OffDelta = 0;
            hv1.PgScroll = PgScrollType.ScreenSizeBased;
            hv1.Size = new Size(622, 252);
            hv1.TabIndex = 9;
            hv1.UnitPg = 512;
            bExportAll.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
            bExportAll.FlatStyle = FlatStyle.Flat;
            bExportAll.Location = new Point(640, 240);
            bExportAll.Name = "bExportAll";
            bExportAll.Size = new Size(59, 46);
            bExportAll.TabIndex = 13;
            bExportAll.Text = "Export &all";
            bExportAll.UseVisualStyleBackColor = true;
            bExportAll.Click += bExportAll_Click;
            bBatExp.AutoSize = true;
            bBatExp.LinkArea = new LinkArea(5, 14);
            bBatExp.Location = new Point(313, 578);
            bBatExp.Name = "bBatExp";
            bBatExp.Size = new Size(104, 17);
            bBatExp.TabIndex = 14;
            bBatExp.TabStop = true;
            bBatExp.Text = "New: &Batch Export!";
            bBatExp.UseCompatibleTextRendering = true;
            bBatExp.LinkClicked += bBatExp_LinkClicked;
            AllowDrop = true;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(711, 632);
            base.Controls.Add(bBatExp);
            base.Controls.Add(bExportAll);
            base.Controls.Add(bExportBin);
            base.Controls.Add(labelHelpMore);
            base.Controls.Add(labelPixi);
            base.Controls.Add(label3);
            base.Controls.Add(bserr);
            base.Controls.Add(label2);
            base.Controls.Add(label1);
            base.Controls.Add(button1);
            base.Controls.Add(lvMI);
            base.Controls.Add(p1);
            base.Controls.Add(linkLabel1);
            base.Controls.Add(treeView1);
            base.Controls.Add(hv1);
            base.Name = "RDForm";
            Text = "map exploring";
            base.Load += RDForm_Load;
            base.DragDrop += RDForm_DragDrop;
            base.DragEnter += RDForm_DragEnter;
            base.ResumeLayout(false);
            base.PerformLayout();
        }
    }
}
